server.port=${PORT:8085}
spring.thymeleaf.cache=false

spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://tataco:1234@cluster0.y9oqqzz.mongodb.net/tacoclouddb?retryWrites=true&w=majority&appName=Cluster0&timeoutMS=30000}
